/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents(); 
        setDefaultCloseOperation(Dashboard.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        bookdetails = new javax.swing.JButton();
        bookavailable = new javax.swing.JButton();
        addbooks = new javax.swing.JButton();
        removedetails = new javax.swing.JButton();
        editadmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");

        bookdetails.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        bookdetails.setText("BOOK DETAILS");
        bookdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookdetailsActionPerformed(evt);
            }
        });

        bookavailable.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        bookavailable.setText("BOOK AVAILABLE");
        bookavailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookavailableActionPerformed(evt);
            }
        });

        addbooks.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        addbooks.setText("ADD BOOKS");
        addbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbooksActionPerformed(evt);
            }
        });

        removedetails.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        removedetails.setText("REMOVE DETAILS");
        removedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removedetailsActionPerformed(evt);
            }
        });

        editadmin.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        editadmin.setText("EDIT ADMIN");
        editadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editadminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(298, 298, 298))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookdetails)
                            .addComponent(addbooks))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removedetails)
                            .addComponent(bookavailable)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(editadmin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addbooks, bookavailable, bookdetails, editadmin, removedetails});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookdetails)
                    .addComponent(bookavailable))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbooks)
                    .addComponent(removedetails))
                .addGap(30, 30, 30)
                .addComponent(editadmin)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addbooks, bookavailable, bookdetails, editadmin, removedetails});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookavailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookavailableActionPerformed
        Books_Available books =  new Books_Available();
        books.setVisible(true);
    }//GEN-LAST:event_bookavailableActionPerformed

    private void bookdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookdetailsActionPerformed
       Book_Details books =  new Book_Details();
        books.setVisible(true);
    }//GEN-LAST:event_bookdetailsActionPerformed

    private void addbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbooksActionPerformed
        Add_Books books =  new Add_Books();
        books.setVisible(true);
    }//GEN-LAST:event_addbooksActionPerformed

    private void removedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removedetailsActionPerformed
         Remove_Books books =  new Remove_Books();
        books.setVisible(true);
    }//GEN-LAST:event_removedetailsActionPerformed

    private void editadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editadminActionPerformed
        EditAdmin Admin =  new EditAdmin();
        Admin.setVisible(true);
    }//GEN-LAST:event_editadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbooks;
    private javax.swing.JButton bookavailable;
    private javax.swing.JButton bookdetails;
    private javax.swing.JButton editadmin;
    private javax.swing.JButton removedetails;
    // End of variables declaration//GEN-END:variables
}
